export const fatosHistoricos = [
  { ano: 1920, fato: "As mulheres ganham o direito ao voto nos EUA" },
  { ano: 1921, fato: "O partido comunista chinês é fundado" },
  { ano: 1922, fato: "O império britânico começa a diminuir" },
  { ano: 1923, fato: "Ocorre o grande terremoto na região de Kanto, no Japão" },
  { ano: 1924, fato: "Joseph Stalin assume o lugar de Vladmir Lenin" },
  { ano: 1925, fato: "O estado americano processa John Thomas Scopes por ensinar evolucionismo em uma escola do Tennessee" },
  { ano: 1926, fato: "Os EUA iniciam o seu sistema de autoestradas numeradas" },
  { ano: 1927, fato: "Charles Lindbergh se torna a primeira pessoa a pilotar um avião sobre o oceano Atlântico sem escalas" },
  { ano: 1928, fato: "Amelia Earhart se torna a primeira mulher a cruzar o Atlântico pilotando um avião" },
  { ano: 1929, fato: "Ocorre a quebra da bolsa de valores de Nova York" },
  { ano: 1930, fato: "Ho Chi Minh funda o partido comunista do Vietnã" },
  { ano: 1931, fato: "A construção do Empire State Building é concluída" },
  { ano: 1932, fato: "Hitler renuncia a sua cidadania austríaca e se torna alemão" },
  { ano: 1933, fato: "Franklin D. Roosevelt é eleito presidente dos Estados Unidos" },
  { ano: 1934, fato: "Hitler se consolida no poder" },
  { ano: 1935, fato: "O presidente Franklin Roosevelt anuncia o New Deal criando o primeiro sistema de seguro social para aposentados do país" },
  { ano: 1936, fato: "Jesse Owens ganha quatro medalhas de ouro nas Olimpíadas de Berlim" },
  { ano: 1937, fato: "Trabalhadores da General Motors protestam por 44 dias e conseguem aumento salarial" },
  { ano: 1938, fato: "O movimento antissemita cresce na Alemanha durante o nazismo de Hitler" },
  { ano: 1939, fato: "Tem início a Segunda Guerra Mundial" },
  { ano: 1940, fato: "O McDonalds é fundado" },
  { ano: 1941, fato: "Tropas japonesas atacam a base de Pearl Harbor" },
  { ano: 1942, fato: "Tropas americanas chegam à Irlanda do Norte para lutar na guerra da Europa" },
  { ano: 1943, fato: "O químico suíço Albert Hofmann descobre acidentalmente o LSD" },
  { ano: 1944, fato: "Ocorre a invasão da Normandia pelas forças aliadas" },
  { ano: 1945, fato: "A Segunda Guerra Mundial termina após ataques atômicos a Hiroshima e Nagasaki" },
  { ano: 1946, fato: "Tem início a geração Baby Boom nos Estados Unidos" },
  { ano: 1947, fato: "A Índia consegue sua independência do Império Britânico" },
  { ano: 1948, fato: "Nasce o Estado de Israel" },
  { ano: 1949, fato: "É fundada a OTAN para combater a ameaça soviética" },
  { ano: 1950, fato: "Tem início a Guerra das Coreias" },
  { ano: 1951, fato: "Julius e Ethel Rosenberg são condenados à morte por espionagem nos EUA" },
  { ano: 1952, fato: "Os Estados Unidos detonam a primeira bomba de hidrogênio" },
  { ano: 1953, fato: "Watson e Crick explicam a estrutura do DNA" },
  { ano: 1954, fato: "A Suprema Corte dos EUA declara inconstitucional a segregação racial nas escolas" },
  { ano: 1955, fato: "Rosa Parks se recusa a ceder seu lugar no ônibus iniciando protestos pelos direitos civis" },
  { ano: 1956, fato: "Protestos na Hungria por democracia são reprimidos pela União Soviética" },
  { ano: 1957, fato: "Tropas federais protegem estudantes afro-americanos em Little Rock" },
  { ano: 1958, fato: "Os Estados Unidos lançam seu primeiro satélite, o Explorer 1" },
  { ano: 1959, fato: "Fidel Castro assume o poder em Cuba" },
  { ano: 1960, fato: "Protestos contra segregação racial começam após recusa de atendimento no restaurante Woolworth" },
  { ano: 1961, fato: "É construído o Muro de Berlim" },
  { ano: 1962, fato: "Crise dos mísseis em Cuba coloca EUA e União Soviética em tensão nuclear" },
  { ano: 1963, fato: "John F. Kennedy é assassinado" },
  { ano: 1964, fato: "Lyndon Johnson inicia a Guerra à Pobreza e aprova o Ato dos Direitos Civis" },
  { ano: 1965, fato: "Protestos do Domingo Sangrento marcam a luta pelos direitos civis" },
  { ano: 1966, fato: "Mao Zedong inicia perseguição a rivais políticos na Revolução Cultural" },
  { ano: 1967, fato: "A Guerra dos Seis Dias ocorre no Oriente Médio" },
  { ano: 1968, fato: "Martin Luther King é assassinado" },
  { ano: 1969, fato: "Neil Armstrong e Buzz Aldrin pisam na Lua" },
  { ano: 1970, fato: "Protestos contra a guerra do Vietnã aumentam nos Estados Unidos" },
  { ano: 1971, fato: "New York Times publica documentos secretos sobre a guerra do Vietnã" },
  { ano: 1972, fato: "Richard Nixon realiza visita histórica à China" },
  { ano: 1973, fato: "Suprema Corte dos EUA define regras sobre aborto no país" },
  { ano: 1974, fato: "Richard Nixon renuncia após o escândalo de Watergate" },
  { ano: 1975, fato: "Saigon é capturada pelas forças comunistas no Vietnã" },
  { ano: 1976, fato: "Voos comerciais do Concorde começam a operar" },
  { ano: 1977, fato: "Os primeiros computadores pessoais modernos começam a surgir" },
  { ano: 1978, fato: "Mais de 900 pessoas morrem em suicídio coletivo em Jonestown" },
  { ano: 1979, fato: "O Irã se torna uma república islâmica" },
  { ano: 1980, fato: "Ronald Reagan é eleito presidente dos Estados Unidos" },
  { ano: 1981, fato: "Casos de AIDS começam a ser identificados nos Estados Unidos" },
  { ano: 1982, fato: "México declara que não consegue pagar sua dívida externa" },
  { ano: 1983, fato: "A internet começa a se desenvolver a partir da ARPANET" },
  { ano: 1984, fato: "Desastre químico em Bhopal, na Índia, mata milhares de pessoas" },
  { ano: 1985, fato: "Reagan se encontra com Mikhail Gorbachev para negociações" },
  { ano: 1986, fato: "A nave Challenger explode após o lançamento" },
  { ano: 1987, fato: "A bolsa Dow Jones sofre grande queda" },
  { ano: 1988, fato: "Escândalo Irã-Contras leva à acusação de oficiais americanos" },
  { ano: 1989, fato: "O Muro de Berlim cai" },
  { ano: 1990, fato: "Polônia encerra regime comunista e elege Lech Walesa" },
  { ano: 1991, fato: "Fim da Guerra Fria após dissolução da União Soviética" },
  { ano: 1992, fato: "É criada a União Europeia" },
  { ano: 1994, fato: "O site Amazon.com é lançado" },
  { ano: 1995, fato: "Ataque terrorista com caminhão-bomba em Oklahoma" },
  { ano: 1996, fato: "A ovelha Dolly é clonada com sucesso" },
  { ano: 1997, fato: "IBM Deep Blue derrota Garry Kasparov no xadrez" },
  { ano: 1998, fato: "É lançado o buscador Google" },
  { ano: 1999, fato: "A OTAN realiza sua primeira campanha militar" },
  { ano: 2000, fato: "A Estação Espacial Internacional é inaugurada" },
  { ano: 2001, fato: "Ataques terroristas derrubam as torres do World Trade Center" },
  { ano: 2002, fato: "George W. Bush cria o Departamento de Segurança Nacional" },
  { ano: 2003, fato: "Os Estados Unidos iniciam a invasão do Iraque" },
  { ano: 2004, fato: "O Facebook é fundado" },
  { ano: 2005, fato: "O furacão Katrina destrói New Orleans" },
  { ano: 2006, fato: "Saddam Hussein é executado" },
  { ano: 2007, fato: "Apple anuncia o primeiro iPhone" },
  { ano: 2008, fato: "Crise financeira faz o índice Dow Jones despencar" },
  { ano: 2009, fato: "Barack Obama se torna o primeiro presidente afro-americano dos EUA" },
  { ano: 2010, fato: "Explosão em plataforma de petróleo no Golfo do México mata trabalhadores" },
  { ano: 2011, fato: "Osama Bin Laden é morto" },
  { ano: 2012, fato: "CERN anuncia evidência do Bóson de Higgs" },
  { ano: 2013, fato: "Edward Snowden revela programas de espionagem dos EUA" },
  { ano: 2014, fato: "Rússia anexa a Crimeia" },
  { ano: 2015, fato: "Sonda New Horizons passa por Plutão" },
  { ano: 2016, fato: "Donald Trump é eleito presidente dos Estados Unidos" },
  { ano: 2017, fato: "Furacões Harvey, Irma e Maria atingem os EUA" },
  { ano: 2018, fato: "Grandes queimadas atingem a Carolina do Norte" },
  { ano: 2019, fato: "Protestos em Hong Kong contra influência da China" },
  { ano: 2020, fato: "Tem início a pandemia de COVID-19" }
];